import test from 'node:test';
import assert from 'node:assert/strict';
import { createAppServer } from '../server.mjs';
let server,base;
test.before(async()=>{server=createAppServer();await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));base=`http://127.0.0.1:${server.address().port}`;});
test.after(async()=>{await new Promise(resolve=>server.close(resolve));});
async function json(path,body,method='POST') {const response=await fetch(base+path,{method,headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});return [response.status,await response.json()];}
test('Health, isolation and homepage',async()=>{const response=await fetch(base+'/');assert.equal(response.status,200);assert.equal(response.headers.get('Cross-Origin-Opener-Policy'),'same-origin');assert.match(await response.text(),/STOR PES6/);const [status,health]=await json('/api/health',null,'GET');assert.equal(status,200);assert.equal(health.ok,true);assert.equal(health.runtime,false);});
test('Safe traversal, missing game and HTTP ranges',async()=>{const noGame=await fetch(base+'/runtime/runtime.js');assert.equal(noGame.status,404);const res=await fetch(base+'/index.html',{headers:{Range:'bytes=0-14'}});assert.equal(res.status,206);assert.equal((await res.arrayBuffer()).byteLength,15);const escaped=await fetch(base+'/%2e%2e/server.mjs');assert.notEqual(escaped.status,200);});
test('Room creation, join, chat and leave',async()=>{const [created,one]=await json('/api/rooms',{name:'Sala brasileira'});assert.equal(created,201);const id=one.room.id;const [joined,a]=await json(`/api/rooms/${id}/join`,{name:'A'});assert.equal(joined,200);const [next,b]=await json(`/api/rooms/${id}/join`,{name:'B'});assert.equal(next,200);const [full]=await json(`/api/rooms/${id}/join`,{name:'C'});assert.equal(full,409);const auth={memberId:a.memberId,token:a.token};const [bad]=await json(`/api/rooms/${id}/chat`,{...auth,token:'wrong',message:'hello'});assert.equal(bad,403);const [chat]=await json(`/api/rooms/${id}/chat`,{...auth,message:'Olá!'});assert.equal(chat,200);const [left]=await json(`/api/rooms/${id}/leave`,{...auth});assert.equal(left,200);const [listStatus,rooms]=await json('/api/rooms',null,'GET');assert.equal(listStatus,200);assert.equal(rooms.rooms.find(x=>x.id===id).count,1);await json(`/api/rooms/${id}/leave`,{memberId:b.memberId,token:b.token});});
